<?php
/**
 * Copyright © Henrique Kieckbusch. All rights reserved.
 * See LICENSE.txt for license details.
 */

/** @var \HenriqueKieckbusch\Jev\Block\Adminhtml\Customer\Edit\Tab\Jev $block */
?>
<div class="admin__page-section-item-content">
    <?= $block->getLayout()->createBlock(\HenriqueKieckbusch\Jev\Block\Adminhtml\Panel::class)
        ->setData('entity_type', 'customer')
        ->setData('entity_id', $block->getCustomerId())
        ->toHtml() ?>
</div>
